
# set pretrained as a file path or an url
pretrained: '/Dataset1/cjw/pretrained/MISS/blipandmedicat_pretrain/checkpoint_69.pth'
# size of vit model; base or large
vit: 'base'
batch_size_train: 16 
batch_size_test: 32 
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 1e-5
image_size: 480

k_test: 128
inference: 'generate'

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 150